### ISSUE TITLE
CMake complains about cyclic dependencies

### ISSUE THREAD

**Issue by erAck** [codilime/veles#309] opened 2017-08-22 10:40 UTC
I did a `git checkout 2017.06.0.SWOND`
`cmake -D CMAKE_BUILD_TYPE=Release ..`
gives
```
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "parser" of type STATIC_LIBRARY
    depends on "veles_db" (weak)
    depends on "parser_autogen" (strong)
  "veles_db" of type STATIC_LIBRARY
    depends on "parser" (weak)
    depends on "veles_db_autogen" (strong)
  "parser_autogen" of type UTILITY
    depends on "veles_db" (strong)
  "veles_db_autogen" of type UTILITY
    depends on "parser" (strong)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
```

**Comment by mkow** [comment] 2017-08-22 17:22
This looks like a duplicate of #290. @koriakin: Could you please take a look at this?

@erAck We'll ping you when this get fixed, for now you can try using older CMake version (3.8 should work AFAIK). Sorry for problems ;)

**Closed by mkow** 2017-08-22 17:22 UTC
Labels: duplicate

**Comment by erAck** [comment] 2017-08-22 21:42
Indeed, using cmake 3.9.0, sorry for duplicate.

**Comment by koriakin** [comment] 2017-09-07 16:56
@erAck This has been fixed in current master.

**Comment by erAck** [comment] 2017-09-13 15:43
I cherry-picked commit 7d973b6779374d45dc415fd24e27652aaa0b8f85 from origin/wip/mwk/cmake-fix onto 2017.06.0.SWOND and can confirm the build now completes. Thanks.
