### ISSUE TITLE
What happened to the blue/orange colors of the point cloud?

### ISSUE THREAD

**Issue by duckythescientist** [codilime/veles#155] opened 2017-04-13 02:59 UTC
The point butt used to be blue/orange to represent location. Is this a setting I'm missing, was this removed, or is this a bug? All the points are just white for me.

`Version: 2017.03.0.Świtezianka`
```
Linux alura 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1070/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 375.39
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL version string: 4.5.0 NVIDIA 375.39
OpenGL shading language version string: 4.50 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 375.39
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by jacek-izykowski** [comment] 2017-04-13 09:46
We expect that to work as it used to.

1) Can you check if you see colours when you switch visualisation to layered digram?
2) Does brightness setting change the situation? Is brightness set to auto?
3) Does it happen with other files too?
4) What kind of file causes this effect? What's the size of file?
5) Can you provide a screenshot or a file itself?

**Comment by mkow** [comment] 2017-06-01 16:20
Couldn't reproduce + no feedback from the reporter, closing.

@duckythescientist: If you want us to look at this issue again please reopen it and provide more info (see the comment above).

**Closed by mkow** 2017-06-01 16:20 UTC
